version: '2'
services: 
  app:
    restart: always
    build: .
    depends_on:
      - mysql
      - redis
      - rabbitmq
    volumes:
      - ~/.m2:/root/.m2
      - .:/tmp
    ports: 
      - "8080:8080"
    command: sh -c "cd /tmp && mvn clean package -DskipTests=true && mv target/*.jar /app.jar && java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
  redis:
    restart: always
    image: daocloud.io/library/redis:latest
  rabbitmq:
    restart: always
    image: daocloud.io/rabbitmq:3
  mysql:
    restart: always
    build: ./mysql/
    environment: 
      - MYSQL_ROOT_PASSWORD=a123456
      
