version: '2'
services: 
  app:
    restart: always
    build: ./app/
    container_name: app
    depends_on:
      - mysql
      - redis
      - rabbitmq
    ports: 
      - "8080:8080"
  redis:
    restart: always
    image: daocloud.io/library/redis:latest
    container_name: redis
    ports: 
      - "6379:6379"
  rabbitmq:
    restart: always
    image: daocloud.io/rabbitmq:3
    container_name: rabbitmq
    ports: 
      - "5672:5672"
  mysql:
    restart: always
    build: ./mysql/
    container_name: mysql
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=a123456
      
