version: '2'
services: 
  redis:
    restart: always
    image: daocloud.io/library/redis:latest
    container_name: redis
    ports: 
      - "6379:6379"
  rabbitmq:
    restart: always
    image: daocloud.io/rabbitmq:3
    container_name: rabbitmq
    ports: 
      - "5672:5672"
  mysql:
    restart: always
    image: daocloud.io/library/mysql:latest
    container_name: mysql
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=a123456
      
