version: '2'
services: 
  app:
    restart: always
    build: .
    container_name: app
    depends_on:
      - mysql
      - redis
      - rabbitmq
    volumes:
      - /root/.m2:/root/.m2
    ports: 
      - "8080:8080"
  redis:
    restart: always
    image: daocloud.io/library/redis:latest
  rabbitmq:
    restart: always
    image: daocloud.io/rabbitmq:3
  mysql:
    restart: always
    build: ./mysql/
    environment: 
      - MYSQL_ROOT_PASSWORD=a123456
      
